version: 2
workflows:
  version: 2
  master:
    jobs:
      # We will run those 3 in parallel
      - code_quality_check
      - unit_tests
      - build
      # Stage environment will be used to run tests
      - deploy_to_stage
        requires:
          - build
        filters:
          branches:
            only: master

      - integration_tests
        requires:
          - deploy_to_stage
      - e2e_tests_stage
        requires:
          - deploy_to_stage
      - deploy_to_preprod
        requires:
          - integration_tests
          - e2e_tests_stage
      - performance_tests
        requires:
          - deploy_to_preprod
      - e2e_tests
        requires:
          - performance_tests
      - deploy_to_prod

jobs:
  code_quality_check:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Run quality tests here"

  unit_tests:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Run unit tests here"

  build:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Run build here"
