# TODO:
# Versioning/Tagging
# Changelog
# Security scanning
# Test results storing
# Modules/code/docker caching
# Deploy of selected version (rollback for example) - needs a hack in CircleCI
# Real jobs explained with:
#   - environment updates
#   - database migrations
#   - versioned secrets


# There are 3 separate flows below:
#
# Flow one is executed for feature/bugfix branches and it aims only to give feedback to developer that his code looks fine and compiles. I assumed that there is no need to have
# "infrastructure per feature" here, so there is no deployment and more complex testing.
#
# Flow two is executed when feature/bugfix branch is going to be merged to master branch. Here we need to have tests which will ensure that this code is safe to be merged and also
# maintain merge queue. My assumption here is that we do not want to pollute master branch and staging environment with faulty application, so we are doing test to avoid it.
#
# Flow three is executed when pull request is actually merged (by flow two). Here we are starting flow to deploy throught testing, preproduction to production environment.
# And again i had to do some assumptions - we deploy to stage immediately after merging, then we want to deploy to preprod/prod in controlled way - with approvals.

version: 2.1
workflows:
  version: 2.1
  master:
    jobs:
      ## We checkout code once
      - code_checkout:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^bugfix\/.*/
                - /^pull\/.*/
                - master
      - list_files
      ## Pipeline to be executed for each commit to the branch
      # We will run those 3 in parallel
      - code_quality_check:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^bugfix\/.*/
      - unit_tests:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^bugfix\/.*/
      - build:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^bugfix\/.*/
          name: build_snapshot

      ## Pipeline section to be executed for each PR to master branch - as far as I see CircleCI is missing thie feature, but there must be possible workaround to just call have 
      ## custom webhook called on PR creation. If it is complicated, webhook may point at AWS Lambda which will then call CircleCI API
      ## Special goal is to ensure that code which will be in trunk branch works
      - preconditions_check:
          filters:
            branches:
              only: /^pull\/.*/
      - lock_merge:
          requires:
            - preconditions_check
      - build:
          requires:
            - lock_merge
          artifact: release-candidate
          name: build_rc
      - deploy:
          requires:
            - build_rc
          environment: dev
          name: deploy_dev
      - functional_tests:
          requires:
            - deploy_dev
          environment: dev
          name: functional_tests_dev
      - integration_tests:
           requires:
             - deploy_dev
           environment: dev
           name: integration_tests_dev
      - preconditions_check:
           requires:
             - functional_tests_dev
             - integration_tests_dev
           name: preconditions_check_final               
      - do_merge:
           requires:
             - preconditions_check_final

      ### Now there is a section which starts once new code is merged. At this point there is also rc artifact available
      ## Staging part
      - deploy:
          environment: stage
          name: deploy_stage
          filters:
            branches:
              only: master
      - functional_tests:
          requires: 
            - deploy_stage
          environment: stage
          name: functional_tests_stage
      - integration_tests:
          requires:
            - deploy_stage
          environment: stage
          name: intergation_tests_stage
      - e2e_tests:
          requires:
            - deploy_stage
          environment: stage
          name: e2e_tests_stage
      
      ## Preprod part - I decided to put only performance tests here, other tests are already done. If infrastructure significantly differs or we want to be super-safe, we can
      ## rerun other tests on preprod
      - preprod_approval:
          type: approval
          requires:
            - functional_tests_stage
            - intergation_tests_stage
            - e2e_tests_stage
      - deploy:
          requires:
            - preprod_approval
          environment: preprod
          name: deploy_preprod
      - performance_tests:
          requires:
            - deploy_preprod
          environment: preprod
          name: performance_tests_preprod

       ## Production part - here we deploy to real production
      - prod_approval:
          type: approval
          requires:
            - performance_tests_preprod
      - mark_artifact_release:
          requires: 
            - prod_approval
      - deploy:
          requires:
            - mark_artifact_release
          environment: prod
          name: deploy_prod
      # Assuming that on prod we cannot run functional/e2e tests - we can only run smoke test and then monitor logs/applications metrics
      - smoke_tests:
          requires:
            - deploy_prod
          environment: prod
          name: smoke_tests_prod

jobs:
  code_quality_check:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Run quality tests here"

  unit_tests:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Run unit tests here"

  build:
    parameters:
      artifact:
        type: string
        default: "snapshot"
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "If artifact is release-candidate then do shallow merge with master"
      - run: echo "Run build here"
      - run: echo "If artifact is snapshot - do not upload artifact, it is only for build test"
      - run: echo "If artifact is release-candidate, do upload artifact to artifact registry"

  deploy:
    parameters:
      environment:
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Deploy to << parameters.environment >> environment"

  preconditions_check:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo "Check if PR preconditions( approvals,etc) are fulfilled. Additinally check if PR has not changed during our flow - if there are approvals removed, code added etc"

  lock_merge:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Check if current lock is connected with pipeline which is still running PR jobs"
      - run: echo "If not, release lock for that pipeline and set new lock"

  do_merge:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Merge PR via Github API"

  functional_tests:
    parameters:
      environment: 
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Run functional tests here for << parameters.environment >>"

  integration_tests:
    parameters:
      environment: 
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Run integration tests here for << parameters.environment >>"

  e2e_tests:
    parameters:
      environment:
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Run E2E tests here for << parameters.environment >>"

  performance_tests:
    parameters:
      environment:
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Run performance tests here for << parameters.environment >>"

  smoke_tests:
    parameters:
      environment:
        type: string
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "Run smoke tests here for << parameters.environment >>"

  mark_artifact_release:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: echo "RC artifact should be changed to release artifact"

  code_checkout:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  list_files:
    working_directory: ~/CobiroAngular
    docker:
      - image: circleci/node:14
    steps:
      - run: ls -al
